### ISSUE TITLE
Adressesøgning fejler på udvalgte adresser på Fyn

### ISSUE THREAD

**Issue by Nyborg1** [gc2vidi/Udvikling-og-vedligeholdelse#10]
Det er ikke muligt at søge adresser på Gl. Vindingevej og Sommerbyen i Nyborg.
Der er ingen fejlmeddelelser - men fejlen optræder i både Geo Fyns VIDI og i Nyborgs VIDI
Vejene og adresserne på vejen findes i AWS og DAWA

**Comment by mapcentia** [comment]
Hej Peter,Jeg har lige sat den til at hente adresser igenSendt fra min iPhoneDen 3. jan. 2023 kl. 08.48 skrev Peter Jørgensen ***@***.***>:﻿
Det er ikke muligt at søge adresser på Gl. Vindingevej i Nyborg.
Der er ingen fejlmeddelelser - men fejlen optræder i både Geo Fyns VIDI og i Nyborgs VIDI

**Comment by Nyborg1** [comment]
Adressesøgningen virker igen. Tak Martin :-)
